site:
  title: BRP API
  start_page: haal-centraal-brp-bevragen::index.adoc
content:
  sources:
  - url: https://github.com/brp-api/haal-centraal-brp-bevragen.git
    branches: antora
ui:
  bundle:
    url: https://github.com/brp-api/antora-ui-bundle/releases/download/v1.0.0/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll