name: Publiceer features

on:
  push:
    branches: ["specs/publish-features-as-md"]
  workflow_dispatch:
    inputs:
      sourceRepository:
        description: 'Publiceer markdown bestanden van deze repository'
        required: true
        default: Haal-Centraal-BRP-bevragen 
        type: choice
        options:
          - Haal-Centraal-BRP-bevragen
          - Haal-Centraal-BRP-bewoning
          - Haal-Centraal-Reisdocumenten-bevragen
          - Haal-Centraal-BRP-historie
jobs:
  move-feature-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: BRP-API/${{ github.event.inputs.sourceRepository || 'Haal-Centraal-BRP-bevragen' }}
          ref: chore/publish-features

      - name: Verplaats .md files van /publish naar /pages/features
        run: |
          mkdir -p pages/features
          mv publish/*.md pages/features

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add pages/features
          git commit -m "Publish features"
